# Use root/example as user/password credentials
version: '3.1'

services:

  mariadb:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: eloRoot$
    volumes:
      - /tmp/mariadb:/var/lib/mysql
    networks:
      - backend


  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    networks:
      - backend
      - frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
