# Use root/example as user/password credentials
version: '3.1'

services:

  mariadb:
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: eloRoot
      MYSQL_USER: elo_user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: elo
    volumes:
      - /tmp/mariadb:/var/lib/mysql
    networks:
      backend:
        aliases:
          - "db"

  adminer:
    image: adminer
    depends_on:
      - "mariadb"
    restart: always
    ports:
      - 8090:8080
    networks:
      - backend
      - frontend

  django:
    image: elo_django:0.0
    build:
      context: .
      dockerfile: Dockerfile.django
    depends_on:
      - "mariadb"
    restart: always
    ports:
      - 8077:8000
    networks:
      - backend
      - frontend

  front:
    image: elo_front:0.0
    build:
      context: .
      dockerfile: Dockerfile.angular
    depends_on:
      - "django"
      - "adminer"
    restart: always
    ports:
      - 8078:80
    networks:
      - frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
